logstash:
  image: logstash
  links:
   - redis
  volumes:
   - $PWD:/config-dir
  command: logstash -f /config-dir/logstash.conf 2> /config-dir/logstash.err > /config-dir/logstash.log

webdis:
  image: anapsix/webdis
  ports:
   - '7379:7379'
  links:
   - redis
  environment:
   THREADS: $THREADS
   POOL_SIZE: $POOL_SIZE
   WEBSOCKETS: $WEBSOCKETS
   ACL_DISABLED: $ACL_DISABLED
   ACL_HTTP_BASIC_AUTH: $ACL_HTTP_BASIC_AUTH
   ACL_HTTP_BASIC_AUTH_ENABLED: $ACL_HTTP_BASIC_AUTH_ENABLED
   VERBOSITY: $VERBOSITY
   LOGFILE: $LOGFILE
   DATABASE: $DATABASE
   REDIS_HOST: $REDIS_HOST
   REDIS_PORT: $REDIS_PORT
   REDIS_AUTH: $REDIS_AUTH
   #volumes:
   # - $PWD/webdis.log:/webdis.log

redis:
  image: redis
